---
apiVersion: v1
kind: Pod
metadata:
  name: pod-config                  # Name of the Pod
spec:
  containers:
    - name: nginx                   # Container name
      image: nginx                  # Uses the official NGINX image
      envFrom:
        - configMapRef:  
            name: nginx-config      # Loads all key-value pairs from ConfigMap 'nginx-config' as environment variables


#envFrom.configMapRef: Injects all key-value pairs from the 'nginx-config'
#kubectl apply -f pod-with-configmap.yaml
#kubectl get po
#kubectl describe po pod-config -> Shows Environment: <none> because envFrom doesn't list variables explicitly in kubectl describe
#kubectl exec -it pod-config -- bash
#env -> Displays ConfigMap data as environment variable

