apiVersion: v1
kind: Pod
metadata:
  name: pod-secret                 # Pod name
spec:
  containers:
    - name: nginx                  # Container running NGINX
      image: nginx
      envFrom:
        - secretRef:
            name: pod-secret       # Load all keys from Secret as environment variables


#envFrom.secretRef: Injects all key-value pairs from the 'pod-secret' as environment variables
#kubectl apply -f pod-with-secret.yaml
#kubectl describe po pod-secret -> Doesn't show secret values
#kubectl exec -it pod-secret -- bash
#env -> Displays Secret data as environment variable
#Inside the container, you can access:
#$Course = AWS DevOps
#$Trainer = Madhu Kiran
#$Institute = MindCircuit Pvt Ltd

