apiVersion: v1
kind: Secret
metadata:
  name: pod-secret                 # Name of the Secret
type: Opaque                       # Generic key-value Secret (base64-encoded)
data:
  Course: QVdTIERldk9wcw==         # "AWS DevOps" (base64-encoded)
  Trainer: TWFkaHUgS2lyYW4=        # "Madhu Kiran"
  Institute: TWluZENpcmN1aXQgUHZ0IEx0ZA==  # "MindCircuit Pvt Ltd"


#kubectl apply -d secret.yaml
#kubectl get secret -> Lists secret
#kubectl describe secret pod-secret -> Shows metadata but not the secret values
