apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: voting-app
    name: postgres-service
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: postgres-pod
    app: voting-app