apiVersion: v1
kind: Pod
metadata:
  name: example-pod               # Name of the Pod
spec:
  containers:
    - name: nginx                 # Container using NGINX image
      image: nginx
      resources:
        requests:                 # Minimum resources the container is guaranteed
          cpu: "500m"             # 0.5 CPU (500 millicores)
          memory: "128Mi"         # 128 MiB memory
        limits:                   # Maximum resources the container can use
          cpu: "1"                # 1 full CPU core
          memory: "256Mi"         # 256 MiB memory

#Summary:
#Requests: Minimum resources allocated (used for scheduling decisions)
#Limits: Maximum resources the container can consume
#Helps prevent resource overuse and ensures fair sharing in a cluster      

#kubectl apply -f pod-resources.yaml
#kubectl get po
#kubectl describe po example-pod -> Shows allocated requests and limits