apiVersion: apps/v1
kind: Deployment
metadata:
  name: fb-deploy
  labels:
    app: facebook
spec:
  replicas: 2
  selector:
    matchLabels:
      app: facebook
  template:
    metadata:
      name: fbpod
      labels:
        app: facebook
    spec:
      nodeSelector:
        env: prod
      containers:
        - name: fbcont1
          image: nginx