apiVersion: apps/v1
kind: Deployment
metadata:
  name: fb-deploy
  labels:
    app: facebook
spec:
  replicas: 2
  selector:
    matchLabels:
      app: facebook
  template:
    metadata:
      name: fbpod
      labels:
        app: facebook
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: env 
                    operator: In
                    values:
                      - prod
                      - sbox
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: topology.kubernetes.io/zone
                    operator: In
                    values:
                      - us-east-1d
              weight: 100
            - preference:
                matchExpressions:
                  - key: Role 
                    operator: NotIn
                    values:
                      - backend
              weight: 50

      containers:
        - name: fbcont1
          image: nginx