apiVersion: v1 
kind: Pod
metadata:
  name: fb-pod
  labels:
    app: facebook
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1a
  tolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "payment"
      effect: "NoExecute"
    - key: "dedicated"
      operator: "Equal"
      value: "payment"
      effect: "NoSchedule"
  containers:
  - name: dbcont
    image: postgres:latest