apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: voting
  labels:
    app: voting-app
    name: redis-service
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    name: redis-pod
    app: voting-app