apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-0b8e5d54286b52b6a

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static
spec:
  storageClassName: ""
  volumeName: ebs-static
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1 
kind: Pod
metadata:
  name: ebs-static-pod
  labels:
    purpose: ebs-static
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1b
  containers:
    - name: facebook
      image: devopshubg333/batch15d:httpd_amazonlinx
      volumeMounts:
        - name: ebs-static
          mountPath: /var/www/html
  volumes:
  - name: ebs-static
    persistentVolumeClaim:
      claimName: ebs-static

---
kind: Service
apiVersion: v1 
metadata:
  name: fb-srv
spec:
  type: LoadBalancer
  selector:
    purpose: ebs-static
  ports:
    - port: 80
      targetPort: 80