---
apiVersion: v1
kind: Pod
metadata:
  name: fbpod
  labels:
    app: facebook
    env: lab
spec:
  containers:
    - name: fbcont
      image: devopshubg333/batch15d:mcfbapp
    - name: tomcatcont
      image: tomcat