apiVersion: v1 
kind: Service
metadata:
  name: nginx-headless
  labels:
    app: nginx 
    demo: statefulset
spec:
  ports:
    - port: 80
      name: web
  clusterIP: None
  selector:
    app: nginx

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
      demo: statefulset
  serviceName: nginx-headless
  replicas: 3
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: nginx
        demo: statefulset
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: nginx
          image: registry.k8s.io/nginx-slim:0.24
          ports:
            - containerPort: 80
              name: web
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: www
  volumeClaimTemplates:
    - metadata:
        name: www
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "ebs-sc"
        resources:
          requests:
            storage: 1Gi

      
    